# Mark issues stale after 1 year
daysUntilStale: 365
# Delete stale issues after 2 years
daysUntilClose: 730
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: >
  This issue has been automatically closed after being marked stale. If you're
  still facing this problem with the above solution, please comment and we'll
  reopen!
