import * as Env from '../Environment.js';

export default {
  Document_createElement: Env.Document.createElement.value,
  Document_createElementNS: Env.Document.createElementNS.value,
  Document_importNode: Env.Document.importNode.value,
  Document_prepend: (Env.Document.prepend || {}).value,
  Document_append: (Env.Document.append || {}).value,
  Node_cloneNode: Env.Node.cloneNode.value,
  Node_appendChild: Env.Node.appendChild.value,
  Node_insertBefore: Env.Node.insertBefore.value,
  Node_removeChild: Env.Node.removeChild.value,
  Node_replaceChild: Env.Node.replaceChild.value,
  Node_textContent: Env.Node.textContent,
  Element_attachShadow: (Env.Element.attachShadow || {}).value,
  Element_innerHTML: Env.Element.innerHTML,
  Element_getAttribute: Env.Element.getAttribute,
  Element_setAttribute: Env.Element.setAttribute,
  Element_removeAttribute: Env.Element.removeAttribute,
  Element_getAttributeNS: Env.Element.getAttributeNS,
  Element_setAttributeNS: Env.Element.setAttributeNS,
  Element_removeAttributeNS: Env.Element.removeAttributeNS,
  Element_insertAdjacentElement: Env.Element['insertAdjacentElement'],
  Element_prepend: Env.Element['prepend'],
  Element_append: Env.Element['append'],
  Element_before: Env.Element['before'],
  Element_after: Env.Element['after'],
  Element_replaceWith: Env.Element['replaceWith'],
  Element_remove: Env.Element['remove'],
  HTMLElement: Env.HTMLElement,
  HTMLElement_innerHTML: Env.HTMLElement.innerHTML,
  HTMLElement_insertAdjacentElement: Env.HTMLElement['insertAdjacentElement'],
};
