# This action requires that any PR targeting the master branch should touch at
# least one CHANGELOG file. If a CHANGELOG entry is not required, add the "Skip
# Changelog" label to disable this action.

name: changelog

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'Skip Changelog')"

    steps:
    - uses: actions/checkout@v2

    - name: Check for CHANGELOG changes
      run: |
        git fetch origin ${{ github.base_ref }} --depth=1
        if [[ $(git diff --name-only FETCH_HEAD | grep CHANGELOG) ]]
        then
          echo "A CHANGELOG was modified. Looks good!"
        else
          echo "No CHANGELOG was modified."
          echo "Please add a CHANGELOG entry, or add the \"Skip Changelog\" label if not required."
          false
        fi
